# Generated by Django 5.0.6 on 2024-06-19 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "drug_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("drug_name", models.CharField(max_length=200)),
                ("drug_name_en", models.CharField(max_length=200)),
                ("drug_material", models.CharField(max_length=50)),
                ("drug_material_code", models.CharField(max_length=200)),
                ("drug_company", models.CharField(max_length=200)),
                ("drug_shape", models.CharField(max_length=20)),
                ("drug_color", models.CharField(max_length=100)),
                (
                    "drug_print_front",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "drug_print_back",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "drug_line_front",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "drug_line_back",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("drug_price_amount", models.FloatField()),
                ("drug_price_unit", models.CharField(max_length=20)),
                ("drug_price", models.IntegerField()),
                ("drug_illness", models.CharField(max_length=20)),
                ("drug_img_key", models.CharField(max_length=400)),
            ],
            options={
                "db_table": "drug",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DrugDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=36)),
                ("drug_no", models.CharField(max_length=20)),
                ("drug_code", models.CharField(blank=True, max_length=20, null=True)),
                ("drug_name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Drug Details",
                "db_table": "drug_details",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DrugImage",
            fields=[
                ("drug_image_id", models.AutoField(primary_key=True, serialize=False)),
                ("drug_imgkey", models.CharField(max_length=200)),
                (
                    "drug_no",
                    models.ForeignKey(
                        db_column="drug_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery_myapp.drug",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drug Images",
                "db_table": "drug_images",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                ("search_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.CharField(max_length=36)),
                ("drug_code", models.CharField(max_length=20)),
                ("search_ip", models.CharField(max_length=20)),
                ("search_date", models.CharField(max_length=100)),
                ("drug_name", models.CharField(max_length=200)),
                ("search_response", models.CharField(max_length=100)),
                (
                    "drug_no",
                    models.ForeignKey(
                        db_column="drug_no",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery_myapp.drug",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search",
                "db_table": "search",
                "managed": True,
            },
        ),
    ]
