# Generated by Django 5.0.6 on 2024-06-20 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discovery_myapp", "0001_initial"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="DrugImage",
        # ),
    ]
